### ISSUE TITLE
Suchformular ist nicht lt. spec

### ISSUE THREAD

**Issue by ri0t** [plus-me/frontend#100]
Das es jetzt wegen dem notch nach oben gewandert ist, mag ja gehn, aber da sind noch fehlerchen:
![Bildschirmfoto_2021-08-25_16-47-28](https://user-images.githubusercontent.com/1938065/130813460-a9919d23-e209-4211-8d8d-434b162061c7.png)

Fällt insbesondere auf, wenn man da noch den Filterpenüppel hindängelt.

Wat tun? 
* Lupe als platzhalter im input? Waaah. Hab ich mal mit angularjs und bootstrap gemacht (ist fies getüddel gewesen)
* lupe weg - ist eh nicht in den specs. verwirrt aber womöglich (specs unklar)

Desweiteren: (@simongogolin :upside_down_face:)
Was macht das kreuz in den specs? Den suchtext löschen (und bei erneutem click das "modal" schliessen?)? Oder nur das "modal" schliessen?

Und was ist eigentlich mit der Notch bzgl. der Inbox-Meine/Alle tabs? Geht dit?

**Comment by enko** [comment]
![Screenshot_+me_20210825-170457](https://user-images.githubusercontent.com/19407/130815825-30c3dec3-3338-42ed-99bf-8ceb212030b0.png)

Hmm, die beiden X sind natürlich nicht so geil. Die Lupe würde ich so lassen, weil standard ionic.

**Comment by enko** [comment]
Bei iOS fällt es nicht so auf

![image](https://user-images.githubusercontent.com/19407/130816249-91b5fbcc-2aca-4100-a01f-48701b50d6dc.png)

**Comment by enko** [comment]
Wenn ich so drüber nachdenke würde ich `showCancelButton` auf `never` stellen, damit würde es erstmal etwas besser aussehen.
