### ISSUE TITLE
Ionic CLI shouldn't be installed locally

### ISSUE THREAD

**Issue by ri0t** [plus-me/frontend#12]
Causes breakage in the build process when trying to build via CLI

**Comment by enko** [comment]
Eher umgekehrt, wenn man eine Ionic CLI global instaliert hat, die inkompatibel mit der lokal installierten Ionic version ist könnte es dinge kaputt machen. 

Der Android Build läuft ja aktuell auch durch:

https://github.com/plus-me/frontend/runs/2992889831?check_suite_focus=true
