### ISSUE TITLE
Userstory für anonyme Nutzer:innen implementieren

### ISSUE THREAD

**Issue by ri0t** [plus-me/frontend#73]
Anonyme Nutzer:innen sollten nach dem Onboarding auf den RandomQuestion-View weitergeleitet werden.
Die Vote-Buttons müssen dann natürlich deaktiviert werden oder automatisch zum Login/Signup auffordern

**Comment by enko** [comment]
Suche soll auch Anonym funktionieren

**Comment by ri0t** [comment]
Ich hab da noch mehr fixes hier zu gehabt, die zum anmelden auffordern, wenn man voten möchte.
Sowohl in question item als auch in bubble.

**Comment by enko** [comment]
Das hab ich schon gemacht, aber IIRC nicht gepushed

**Comment by enko** [comment]
Hatte das in den state eingebaut: https://github.com/plus-me/frontend/commit/05624ad4f5df74f440dcb7503c933b0bae99425c#diff-a68842653536b9e2c70a8ffeddb0e227013a5e26d4d7463bb19c228220c13914
