### ISSUE TITLE
Tap auf Tag macht nichts

### ISSUE THREAD

**Issue by enko** [plus-me/frontend#89]
Erwartung: Wenn man auf den Tag tippt, dann sollte die Suche mit dem Tag ausgeführt werden.

Bonus: Tags tauchen in der Suche nicht auf

**Comment by ri0t** [comment]
Willst Du in der Antworten-Liste mit tap auf ein tag alle fragen in der suche sehen, oder nur beantwortete fragen mit dem tag? Letzteres ist aktuell auch vom backend vermutlich nicht vorgesehen.

**Comment by enko** [comment]
Einfach den Tag-Text in die Suche machen

**Comment by ri0t** [comment]
Ok.
