### ISSUE TITLE
Fragen aus der Suche +me

### ISSUE THREAD

**Issue by enko** [plus-me/frontend#93]
https://www.figma.com/file/2UHS7rjlCXkK0rK16GMpOt/Wepublic-%2Bme-2021?node-id=2429%3A22771

**Comment by ri0t** [comment]
Was ist hier genau zu tun?

**Comment by ri0t** [comment]
Der upvote button? Is schon länger drin... Hmmm?

**Comment by enko** [comment]
Weis auch nicht mehr, würde das Issue erstmal schließen.
